### ISSUE TITLE
Unknown color name "SystemButtonFace"

### ISSUE THREAD

**Issue by szabopeter** [herobank110/factorygame#8]
When running run_test.py, the ActionDestroy entry did not work, a Tcl exception was raised.

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1886, in __call__
    return self.func(*args)
  File "/usr/lib/python3.8/tkinter/__init__.py", line 807, in callit
    func(*args)
  File "***/factorygame/test/template/template_gui.py", line 86, in <lambda>
    self.after(0, lambda e=e: self.on_test_list_pressed(e)))
  File "***/factorygame/test/template/template_gui.py", line 132, in on_test_list_pressed
    new_wgt = test_class(self)
  File "***/factorygame/test/template/template_gui.py", line 41, in __init__
    self.start()
  File "***/factorygame/test/core/engine_test.py", line 126, in start
    t = Text(
  File "/usr/lib/python3.8/tkinter/__init__.py", line 3557, in __init__
    Widget.__init__(self, master, 'text', cnf, kw)
  File "/usr/lib/python3.8/tkinter/__init__.py", line 2570, in __init__
    self.tk.call(
_tkinter.TclError: unknown color name "SystemButtonFace"
```

**Comment by szabopeter** [comment]
I'll commit a fix shortly.
